### PR TITLE
Increase verbosity of configure and build phase

### PR DESCRIPTION
**Pull request by mimi1vx**

### CODE REVIEW

**Comment by juhp** [comment]
What is the main benefit of doing this?

**Comment by peti** [comment]
We need the verbose `configure` output in our build logs. The addition of `-v` to `build` and `test` is less important.

**Comment by juhp** [comment]
Okay, let me try myself.  Any particular examples or use cases?
I guess I would like to understand why you need it?

**Comment by peti** [comment]
Without "-v" the build log won't show which Cabal flags were chosen
during the configure phase. Neither will the log show which versions of
the dependencies will be used for compilation.

**Comment by mimi1vx** [comment]
now is used in devel:languages:haskell:lts repository.

I plan submit this change to openSUSE: Tumbleweed in next week

an example : https://build.opensuse.org/build/devel:languages:haskell:lts/openSUSE_Tumbleweed/x86_64/git-annex/_log

plus in OBS can run automatic checks using build log files.

**Comment by juhp** [comment]
Okay: then how about just for configure?

**Comment by mimi1vx** [comment]
we can analyze build logs in OBS in automatic checks .. and -v is only
verbose=2 , default is verbose=1..

isn't big overhead and openSUSE packaging recomends ( also for security
reasons ) verbose build

plus verbose build is very helpful for analyze problems with macros..

**Comment by juhp** [comment]
Alright, I can merge this, but I think I prefer to do it with a macro which could be defined per OS.
We don't really need this in Fedora but I can see you need it for openSUSE.

Not sure what the best name would be:  %cabal_verbose or maybe something more generic?

Edit: ~~Additionally -v could be moved to the definition of %cabal itself perhaps, so that all instantiations would be verbose if that is desirable?~~ Nevermind Setup does not accept `-v` before a command.

**Comment by juhp** [comment]
Any thoughts on making %cabal always verbose for openSUSE?

**Comment by juhp** [comment]
Okay I pushed %cabal_verbose - admittedly untested and the name can still be changed if needed.
Currently to use it you would need to add either a `macros.ghc-suse` file say with `%cabal_verbose -v` or append it to `macros.ghc` say to use it - again open to better suggestions.

**Pull request merged**
